---

- name: Update Uptime Kuma
  hosts: 192.168.0.10
  become: false  # Run tasks with elevated privileges (sudo)

  tasks:
    - name: Docker Pull
      command: docker pull louislam/uptime-kuma:1

    - name: docker stop uptime-kuma
      command: docker stop uptime-kuma

    - name: docker rm uptime-kuma
      command: docker rm uptime-kuma

    - name: Restart uptime-kuma
      command: docker run -d --restart=always -p 3001:3001 -v uptime-kuma:/app/data --name uptime-kuma louislam/uptime-kuma:1
